spring.application.name=gestion_partes

# --- CONFIGURACION DE CONEXION ---
# Si existe la variable en el entorno, la usa. Si no, apunta a localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.your-tenant-id}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your-super-secret-and-long-postgres-password}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SHOW_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- SEGURIDAD Y JWT ---
jwt.secret=${JWT_SECRET:your-super-secret-jwt-token-with-at-least-32-characters-long}

# --- SUPABASE API ---
# En Docker usaremos el nombre del servicio, en local localhost
supabase.url=${SUPABASE_URL:http://localhost:8000}
supabase.service.key=${SUPABASE_SERVICE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q}

# --- SERVER ---
server.port=${SERVER_PORT:8081}
logging.level.org.springframework.security=DEBUG

# --- JACKSON ---
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.serialization.fail-on-empty-beans=false

# --- APK ---
app.version.actual=1.0.8
app.apk.url=http://gestion-partes.duckdns.org:/storage/v1/object/public/instaladores/app-release.apk