-- ==========================================
-- 1. LIMPIEZA TOTAL
-- ==========================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.partes_trabajo CASCADE;
DROP TABLE IF EXISTS public.perfiles CASCADE;
DROP TABLE IF EXISTS public.obras CASCADE;
DROP TYPE IF EXISTS public.usuario_rol CASCADE;

-- ==========================================
-- 2. TIPOS Y ESTRUCTURA
-- ==========================================
CREATE TYPE public.usuario_rol AS ENUM (
    'ADMINISTRACION',
    'GESTION',
    'OPERARIO',
    'JEFE_DE_OBRA',
    'ENCARGADO_DE_OBRA'
    );

CREATE TABLE public.obras (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nombre TEXT NOT NULL,
                              ubicacion TEXT NOT NULL,
                              municipio TEXT NOT NULL,
                              poblacion TEXT NOT NULL,
                              fecha_inicio DATE DEFAULT CURRENT_DATE,
                              activa BOOLEAN DEFAULT TRUE,
                              creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.perfiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE,
    nombre_completo TEXT,
    password TEXT,
    rol usuario_rol DEFAULT 'OPERARIO',
    activo BOOLEAN DEFAULT TRUE,
    creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.partes_trabajo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
    point_obra_id BIGINT REFERENCES public.obras(id) ON DELETE SET NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    horas_normales DECIMAL(4,2) DEFAULT 8.0,
    horas_extra DECIMAL(4,2) DEFAULT 0.0,
    descripcion_tareas TEXT,
    firmado BOOLEAN DEFAULT FALSE,
    creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 3. SEGURIDAD RLS (CORRECCIÓN DE RENDIMIENTO FINAL)
-- ==========================================
ALTER TABLE public.obras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partes_trabajo ENABLE ROW LEVEL SECURITY;

-- SOLUCIÓN AL ISSUE DE "OBRAS": Usamos (select auth.role())
CREATE POLICY "Lectura global de obras" ON public.obras
    FOR SELECT USING ((select auth.role()) = 'authenticated');

-- SOLUCIÓN AL ISSUE DE "PERFILES"
CREATE POLICY "Cada uno ve su perfil" ON public.perfiles
    FOR SELECT USING ((select auth.uid()) = id);

-- SOLUCIÓN AL ISSUE DE "PARTES_TRABAJO"
CREATE POLICY "Cada uno ve sus partes" ON public.partes_trabajo
    FOR SELECT USING ((select auth.uid()) = usuario_id);

CREATE POLICY "Usuarios insertan sus partes" ON public.partes_trabajo
    FOR INSERT WITH CHECK ((select auth.uid()) = usuario_id);

-- ==========================================
-- 4. AUTOMATIZACIÓN E ÍNDICES
-- ==========================================
CREATE INDEX idx_perfiles_rol ON public.perfiles(rol);
CREATE INDEX idx_partes_usuario_id ON public.partes_trabajo(usuario_id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = public
AS $$
BEGIN
    INSERT INTO public.perfiles (id, email, nombre_completo, rol)
    VALUES (
               new.id,
               new.email,
               COALESCE(new.raw_user_meta_data->>'full_name', 'Nuevo Usuario'),
               'OPERARIO'
           );
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 5. DATOS INICIALES
-- ==========================================
INSERT INTO public.obras (nombre, ubicacion, municipio, poblacion)
VALUES
    ('Castanyete 3', 'Calle Castanyete 3', 'Palma', 'Palma'),
    ('Solleric 3', 'Plaza Solleric', 'Sóller', 'Sóller');