-- ==========================================
-- 1. LIMPIEZA TOTAL
-- ==========================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.asignaciones_obra CASCADE;
DROP TABLE IF EXISTS public.asignaciones_encargado CASCADE;
DROP TABLE IF EXISTS public.partes_trabajo CASCADE;
DROP TABLE IF EXISTS public.perfiles CASCADE;
DROP TABLE IF EXISTS public.obras CASCADE;
DROP TYPE IF EXISTS public.usuario_rol CASCADE;

-- ==========================================
-- 2. TIPOS Y ESTRUCTURA
-- ==========================================
CREATE TYPE public.usuario_rol AS ENUM (
    'ADMINISTRACION',
    'GESTION',
    'OPERARIO',
    'JEFE_DE_OBRA',
    'ENCARGADO'
    );

CREATE TABLE public.obras (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nombre TEXT NOT NULL,
                              ubicacion TEXT NOT NULL,
                              municipio TEXT NOT NULL,
                              poblacion TEXT NOT NULL,
                              fecha_inicio DATE DEFAULT CURRENT_DATE,
                              activa BOOLEAN DEFAULT TRUE,
                              creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.perfiles (
                                 id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
                                 email TEXT UNIQUE,
                                 nombre_completo TEXT,
                                 rol public.usuario_rol DEFAULT 'OPERARIO',
                                 jefe_directo_id UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
                                 activo BOOLEAN DEFAULT TRUE,
                                 creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Qué perfil está asignado a qué obra (jefes, encargados, operarios)
CREATE TABLE public.asignaciones_obra (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          perfil_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
                                          obra_id BIGINT REFERENCES public.obras(id) ON DELETE CASCADE,
                                          fecha_asignacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                                          CONSTRAINT unica_asignacion_perfil_obra UNIQUE(perfil_id, obra_id)
);

-- Dentro de una obra, qué operarios están bajo qué encargado
CREATE TABLE public.asignaciones_encargado (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               encargado_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
                                               operario_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
                                               obra_id BIGINT REFERENCES public.obras(id) ON DELETE CASCADE,
                                               fecha_asignacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                                               CONSTRAINT unica_asignacion_operario_obra UNIQUE(operario_id, obra_id)
);

CREATE TABLE public.partes_trabajo (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       usuario_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
                                       point_obra_id BIGINT REFERENCES public.obras(id) ON DELETE SET NULL,
                                       fecha DATE DEFAULT CURRENT_DATE,
                                       horas_normales DECIMAL(4,2) DEFAULT 8.0,
                                       horas_extra DECIMAL(4,2) DEFAULT 0.0,
                                       descripcion_tareas TEXT,
                                       firmado BOOLEAN DEFAULT FALSE,
                                       creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 3. SIN RLS — Spring Boot controla la seguridad
-- ==========================================
ALTER TABLE public.obras DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.asignaciones_obra DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.asignaciones_encargado DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.partes_trabajo DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- 4. ÍNDICES
-- ==========================================
CREATE INDEX idx_perfiles_rol ON public.perfiles(rol);
CREATE INDEX idx_perfiles_jefe ON public.perfiles(jefe_directo_id);
CREATE INDEX idx_asignacion_obra_perfil ON public.asignaciones_obra(perfil_id);
CREATE INDEX idx_asignacion_obra_obra ON public.asignaciones_obra(obra_id);
CREATE INDEX idx_asignacion_encargado ON public.asignaciones_encargado(encargado_id);
CREATE INDEX idx_asignacion_operario ON public.asignaciones_encargado(operario_id);
CREATE INDEX idx_partes_usuario_id ON public.partes_trabajo(usuario_id);
CREATE INDEX idx_partes_obra_id ON public.partes_trabajo(point_obra_id);

-- ==========================================
-- 5. TRIGGER: crear perfil al registrar usuario
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    INSERT INTO public.perfiles (id, email, nombre_completo, rol)
    VALUES (
               new.id,
               new.email,
               COALESCE(new.raw_user_meta_data->>'full_name', 'Nuevo Usuario'),
               COALESCE(
                       (new.raw_user_meta_data->>'rol')::public.usuario_rol,
                       'OPERARIO'
               )
           );
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 6. DATOS INICIALES
-- ==========================================
INSERT INTO public.obras (nombre, ubicacion, municipio, poblacion)
VALUES ('Castanyete 3', 'Calle Castanyete 3', 'Palma', 'Palma');