-- ==========================================
-- 1. LIMPIEZA TOTAL
-- ==========================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.partes_jefe_obras CASCADE;
DROP TABLE IF EXISTS public.partes_jefe CASCADE;
DROP TABLE IF EXISTS public.asignaciones_obra CASCADE;
DROP TABLE IF EXISTS public.partes_trabajo CASCADE;
DROP TABLE IF EXISTS public.perfiles CASCADE;
DROP TABLE IF EXISTS public.obras CASCADE;
DROP TYPE IF EXISTS public.usuario_rol CASCADE;

-- ==========================================
-- 2. TIPOS Y ESTRUCTURA
-- ==========================================
CREATE TYPE public.usuario_rol AS ENUM (
    'ADMINISTRACION',
    'GESTION',
    'OPERARIO',
    'JEFE_DE_OBRA',
    'ENCARGADO'
    );

CREATE TABLE public.obras (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nombre TEXT NOT NULL,
                              ubicacion TEXT NOT NULL,
                              municipio TEXT NOT NULL,
                              poblacion TEXT NOT NULL,
                              fecha_inicio DATE DEFAULT CURRENT_DATE,
                              activa BOOLEAN DEFAULT TRUE,
                              creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.perfiles (
                                 id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
                                 email TEXT UNIQUE,
                                 nombre_completo TEXT,
                                 codigo TEXT UNIQUE,                          -- nuevo: código del operario/encargado
                                 rol public.usuario_rol DEFAULT 'OPERARIO',
                                 jefe_directo_id UUID REFERENCES public.perfiles(id) ON DELETE SET NULL,
                                 activo BOOLEAN DEFAULT TRUE,
                                 creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.asignaciones_obra (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          perfil_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
                                          obra_id BIGINT REFERENCES public.obras(id) ON DELETE CASCADE,
                                          fecha_asignacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                                          CONSTRAINT unica_asignacion_perfil_obra UNIQUE(perfil_id, obra_id)
);

-- Partes de operarios y encargados
CREATE TABLE public.partes_trabajo (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       usuario_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
                                       point_obra_id BIGINT REFERENCES public.obras(id) ON DELETE SET NULL,
                                       fecha DATE NOT NULL,
                                       horas_normales DECIMAL(4,2) DEFAULT 8.0,
                                       horas_extra DECIMAL(4,2) DEFAULT 0.0,
                                       descripcion_tareas TEXT,
                                       firmado BOOLEAN DEFAULT FALSE,
                                       creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- Límite: la fecha del parteJefe no puede ser anterior a 2 semanas
                                       CONSTRAINT fecha_max_dos_semanas CHECK (fecha >= CURRENT_DATE - INTERVAL '14 days')
);

-- Partes de jefes de obra (fecha automática, porcentajes por obra)
CREATE TABLE public.partes_jefe (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    usuario_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
                                    fecha DATE DEFAULT CURRENT_DATE,
                                    descripcion_tareas TEXT,
                                    firmado BOOLEAN DEFAULT FALSE,
                                    creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.partes_jefe_obras (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          parte_jefe_id BIGINT REFERENCES public.partes_jefe(id) ON DELETE CASCADE,
                                          obra_id BIGINT REFERENCES public.obras(id) ON DELETE SET NULL,
                                          porcentaje DECIMAL(5,2) NOT NULL,
                                          CONSTRAINT porcentaje_valido CHECK (porcentaje > 0 AND porcentaje <= 100)
);

ALTER TABLE public.partes_jefe DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.partes_jefe_obras DISABLE ROW LEVEL SECURITY;

CREATE INDEX idx_partes_jefe_usuario ON public.partes_jefe(usuario_id);
CREATE INDEX idx_partes_jefe_obras ON public.partes_jefe_obras(parte_jefe_id);

-- ==========================================
-- 3. SIN RLS
-- ==========================================
ALTER TABLE public.obras DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.asignaciones_obra DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.partes_trabajo DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.partes_jefe DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.partes_jefe_obras DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- 4. ÍNDICES
-- ==========================================
-- ==========================================
-- 4. ÍNDICES (Corregido: sin duplicados)
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_perfiles_rol ON public.perfiles(rol);
CREATE INDEX IF NOT EXISTS idx_perfiles_jefe ON public.perfiles(jefe_directo_id);
CREATE INDEX IF NOT EXISTS idx_perfiles_codigo ON public.perfiles(codigo);
CREATE INDEX IF NOT EXISTS idx_asignacion_obra_perfil ON public.asignaciones_obra(perfil_id);
CREATE INDEX IF NOT EXISTS idx_asignacion_obra_obra ON public.asignaciones_obra(obra_id);
CREATE INDEX IF NOT EXISTS idx_partes_usuario_id ON public.partes_trabajo(usuario_id);
CREATE INDEX IF NOT EXISTS idx_partes_obra_id ON public.partes_trabajo(point_obra_id);

-- Estos son los que daban el error por estar repetidos arriba:
CREATE INDEX IF NOT EXISTS idx_partes_jefe_usuario_v2 ON public.partes_jefe(usuario_id);
CREATE INDEX IF NOT EXISTS idx_partes_jefe_obras_v2 ON public.partes_jefe_obras(parte_jefe_id);

-- ==========================================
-- 5. TRIGGER
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    INSERT INTO public.perfiles (id, email, nombre_completo, rol)
    VALUES (
               new.id,
               new.email,
               COALESCE(new.raw_user_meta_data->>'full_name', 'Nuevo Usuario'),
               COALESCE(
                       (new.raw_user_meta_data->>'rol')::public.usuario_rol,
                       'OPERARIO'
               )
           );
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 6. DATOS INICIALES
-- ==========================================
INSERT INTO public.obras (nombre, ubicacion, municipio, poblacion)
VALUES ('Castanyete 3', 'Calle Castanyete 3', 'Palma', 'Palma');