-- =============================================
-- TIPOS
-- =============================================

CREATE TYPE public.usuario_rol AS ENUM (
    'ADMINISTRACION',
    'GESTION',
    'OPERARIO',
    'JEFE_DE_OBRA',
    'ENCARGADO'
);

CREATE TYPE public.ausencia_tipo AS ENUM ('BAJA', 'VACACIONES', 'PATERNIDAD');

-- =============================================
-- TABLAS
-- =============================================

CREATE TABLE public.perfiles (
                                 id                uuid NOT NULL,
                                 email             text,
                                 nombre            text,
                                 apellidos         text,
                                 codigo            text,
                                 rol               public.usuario_rol DEFAULT 'OPERARIO'::public.usuario_rol,
                                 jefe_directo_id   uuid,
                                 activo            boolean DEFAULT true,
                                 postventa         boolean DEFAULT false,
                                 especialidad      text,
                                 grupo_profesional text,
                                 creado_el         timestamp with time zone DEFAULT now(),
                                 CONSTRAINT perfiles_pkey        PRIMARY KEY (id),
                                 CONSTRAINT perfiles_email_key   UNIQUE (email),
                                 CONSTRAINT perfiles_codigo_key  UNIQUE (codigo),
                                 CONSTRAINT perfiles_especialidad_check
                                     CHECK (especialidad = ANY (ARRAY['ELECTRICIDAD'::text, 'FONTANERIA'::text]))
);

CREATE TABLE public.obras (
                              id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nombre     text NOT NULL,
                              ubicacion  text NOT NULL,
                              municipio  text NOT NULL,
                              poblacion  text NOT NULL,
                              codigo     text NOT NULL,
                              activa     boolean DEFAULT true,
                              creado_el  timestamp with time zone DEFAULT now(),
                              postventa   boolean DEFAULT false,
                              CONSTRAINT obras_codigo_key UNIQUE (codigo)
);

CREATE TABLE public.asignaciones_obra (
                                          id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          perfil_id         uuid,
                                          obra_id           bigint,
                                          fecha_asignacion  timestamp with time zone DEFAULT now(),
                                          CONSTRAINT unica_asignacion_perfil_obra UNIQUE (perfil_id, obra_id)
);

CREATE TABLE public.partes_trabajo (
                                       id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       usuario_id         uuid REFERENCES public.perfiles(id) ON DELETE CASCADE,
                                       point_obra_id      bigint REFERENCES public.obras(id) ON DELETE SET NULL,
                                       fecha              date NOT NULL,
                                       horas_normales     numeric(4,2) DEFAULT 8.0,
                                       horas_extra        numeric(4,2) DEFAULT 0.0,
                                       descripcion_tareas text,
                                       especialidad       text CHECK (especialidad IN ('ELECTRICIDAD', 'FONTANERIA')),
                                       creado_por_gestor  boolean NOT NULL DEFAULT FALSE,
                                       firma_url          text,
                                       nombre_firmador    text,
                                       trabajos_extra     text,
                                       creado_el          timestamp with time zone DEFAULT now()
);

CREATE TABLE public.partes_jefe (
                                    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    usuario_id            uuid,
                                    fecha                 date DEFAULT CURRENT_DATE,
                                    descripcion_tareas    text,
                                    fecha_inicio          date,
                                    fecha_fin             date,
                                    total_horas_laborables numeric(8,2),
                                    creado_el             timestamp with time zone DEFAULT now()
);

CREATE TABLE public.partes_jefe_obras (
                                          id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          parte_jefe_id        bigint,
                                          obra_id              bigint,
                                          horas_electricas     numeric(8,2) NOT NULL DEFAULT 0,
                                          horas_mecanicas      numeric(8,2) NOT NULL DEFAULT 0,
                                          porcentaje_electrico numeric(5,2) NOT NULL DEFAULT 0,
                                          porcentaje_mecanico  numeric(5,2) NOT NULL DEFAULT 0
);

CREATE TABLE public.fechas_permitidas (
                                          id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          perfil_id  uuid NOT NULL,
                                          fecha      date NOT NULL,
                                          creado_el  timestamp with time zone DEFAULT now(),
                                          CONSTRAINT unica_fecha_perfil UNIQUE (perfil_id, fecha),
                                          CONSTRAINT fechas_permitidas_perfil_id_fkey
                                              FOREIGN KEY (perfil_id) REFERENCES public.perfiles(id) ON DELETE CASCADE
);

CREATE TABLE public.ausencias (
                                  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  perfil_id    uuid NOT NULL,
                                  tipo         public.ausencia_tipo NOT NULL,
                                  fecha_inicio date NOT NULL,
                                  fecha_fin    date NOT NULL,
                                  observaciones text,
    -- obra_id solo se usa cuando tipo = 'VACACIONES'.
    -- NULL → imputa a oficina (LUM); valor → imputa a esa obra en la quincena.
                                  obra_id      bigint,
                                  creado_el    timestamp with time zone DEFAULT now(),
                                  CONSTRAINT ausencias_perfil_id_fkey
                                      FOREIGN KEY (perfil_id) REFERENCES public.perfiles(id) ON DELETE CASCADE,
                                  CONSTRAINT ausencias_obra_id_fkey
                                      FOREIGN KEY (obra_id) REFERENCES public.obras(id) ON DELETE SET NULL
);

-- =============================================
-- FOREIGN KEYS
-- =============================================

ALTER TABLE public.perfiles
    ADD CONSTRAINT perfiles_id_fkey
        FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE,
    ADD CONSTRAINT perfiles_jefe_directo_id_fkey
        FOREIGN KEY (jefe_directo_id) REFERENCES public.perfiles(id) ON DELETE SET NULL;

ALTER TABLE public.asignaciones_obra
    ADD CONSTRAINT asignaciones_obra_perfil_id_fkey
        FOREIGN KEY (perfil_id) REFERENCES public.perfiles(id) ON DELETE CASCADE,
    ADD CONSTRAINT asignaciones_obra_obra_id_fkey
        FOREIGN KEY (obra_id) REFERENCES public.obras(id) ON DELETE CASCADE;

ALTER TABLE public.partes_trabajo
    ADD CONSTRAINT partes_trabajo_usuario_id_fkey
        FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE CASCADE,
    ADD CONSTRAINT partes_trabajo_point_obra_id_fkey
        FOREIGN KEY (point_obra_id) REFERENCES public.obras(id) ON DELETE SET NULL;

ALTER TABLE public.partes_jefe
    ADD CONSTRAINT partes_jefe_usuario_id_fkey
        FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;

ALTER TABLE public.partes_jefe_obras
    ADD CONSTRAINT partes_jefe_obras_parte_jefe_id_fkey
        FOREIGN KEY (parte_jefe_id) REFERENCES public.partes_jefe(id) ON DELETE CASCADE,
    ADD CONSTRAINT partes_jefe_obras_obra_id_fkey
        FOREIGN KEY (obra_id) REFERENCES public.obras(id) ON DELETE SET NULL;

-- =============================================
-- ÍNDICES
-- =============================================

CREATE INDEX idx_perfiles_rol            ON public.perfiles          USING btree (rol);
CREATE INDEX idx_perfiles_jefe           ON public.perfiles          USING btree (jefe_directo_id);
CREATE INDEX idx_perfiles_codigo         ON public.perfiles          USING btree (codigo);

CREATE INDEX idx_asignacion_obra_perfil  ON public.asignaciones_obra USING btree (perfil_id);
CREATE INDEX idx_asignacion_obra_obra    ON public.asignaciones_obra USING btree (obra_id);

CREATE INDEX idx_partes_usuario_id       ON public.partes_trabajo    USING btree (usuario_id);
CREATE INDEX idx_partes_obra_id          ON public.partes_trabajo    USING btree (point_obra_id);

CREATE INDEX idx_partes_jefe_usuario     ON public.partes_jefe       USING btree (usuario_id);
CREATE INDEX idx_partes_jefe_obras       ON public.partes_jefe_obras USING btree (parte_jefe_id);

CREATE INDEX idx_fechas_permitidas_perfil ON public.fechas_permitidas USING btree (perfil_id);
CREATE INDEX idx_fechas_permitidas_fecha  ON public.fechas_permitidas USING btree (fecha);

CREATE INDEX idx_ausencias_perfil        ON public.ausencias         USING btree (perfil_id);
CREATE INDEX idx_ausencias_fechas        ON public.ausencias         USING btree (fecha_inicio, fecha_fin);
CREATE INDEX idx_ausencias_obra          ON public.ausencias         USING btree (obra_id);

CREATE INDEX idx_partes_trabajo_informe_obra ON public.partes_trabajo (point_obra_id, fecha);
CREATE INDEX idx_partes_trabajo_informe_usuario ON public.partes_trabajo (usuario_id, fecha);
CREATE INDEX idx_ausencias_solapamiento     ON public.ausencias (perfil_id, fecha_inicio, fecha_fin);
CREATE INDEX idx_partes_trabajo_fecha   ON public.partes_trabajo (fecha);
-- =============================================
-- FUNCIONES Y TRIGGERS
-- =============================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
INSERT INTO public.perfiles (
    id, email, nombre, apellidos, rol, activo,
    especialidad, codigo, postventa, grupo_profesional
) VALUES (
             new.id,
             new.email,
             COALESCE(new.raw_user_meta_data->>'nombre', ''),
             COALESCE(new.raw_user_meta_data->>'apellidos', ''),
             COALESCE(new.raw_user_meta_data->>'rol', 'OPERARIO')::public.usuario_rol,
             true,
             COALESCE(new.raw_user_meta_data->>'especialidad', 'ELECTRICIDAD'),
             new.raw_user_meta_data->>'codigo',
             COALESCE((new.raw_user_meta_data->>'postventa')::boolean, false),
             new.raw_user_meta_data->>'grupo_profesional'
         );
RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.sync_user_role()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
Set search_path = public, pg_catalog
AS $$
BEGIN
UPDATE auth.users
SET raw_user_meta_data = jsonb_set(raw_user_meta_data, '{rol}', TO_JSONB(NEW.rol))
WHERE id = NEW.id;
RETURN NEW;
END;
$$;

-- =============================================
-- MIGRACIÓN (si la BD ya existe)
-- Ejecutar solo si la tabla ausencias ya tiene datos
-- =============================================

-- ALTER TABLE public.ausencias
--     ADD COLUMN IF NOT EXISTS obra_id bigint,
--     ADD CONSTRAINT ausencias_obra_id_fkey
--         FOREIGN KEY (obra_id) REFERENCES public.obras(id) ON DELETE SET NULL;
--
-- CREATE INDEX IF NOT EXISTS idx_ausencias_obra
--     ON public.ausencias USING btree (obra_id);