CREATE SCHEMA public;
ALTER SCHEMA public OWNER TO pg_database_owner;

CREATE TYPE public.usuario_rol AS ENUM (
    'ADMINISTRACION',
    'GESTION',
    'OPERARIO',
    'JEFE_DE_OBRA',
    'ENCARGADO'
);
ALTER TYPE public.usuario_rol OWNER TO supabase_admin;

CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
INSERT INTO public.perfiles (id, email, nombre_completo, rol)
VALUES (
           new.id,
           new.email,
           COALESCE(new.raw_user_meta_data->>'full_name', 'Nuevo Usuario'),
           COALESCE(
                   (new.raw_user_meta_data->>'rol')::public.usuario_rol,
                   'OPERARIO'
           )
       );
RETURN NEW;
END;
$$;
ALTER FUNCTION public.handle_new_user() OWNER TO supabase_admin;

SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE public.asignaciones_obra (
    id bigint NOT NULL,
    perfil_id uuid,
    obra_id bigint,
    fecha_asignacion timestamp with time zone DEFAULT now()
);
ALTER TABLE public.asignaciones_obra OWNER TO supabase_admin;

ALTER TABLE public.asignaciones_obra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asignaciones_obra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.obras (
    id bigint NOT NULL,
    nombre text NOT NULL,
    ubicacion text NOT NULL,
    municipio text NOT NULL,
    poblacion text NOT NULL,
    codigo text NOT NULL UNIQUE ,
    activa boolean DEFAULT true,
    creado_el timestamp with time zone DEFAULT now(),
    especialidad TEXT CHECK (especialidad IN ('ELECTRICIDAD', 'FONTANERIA'))
);
ALTER TABLE public.obras OWNER TO supabase_admin;

ALTER TABLE public.obras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.obras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.partes_jefe (
    id bigint NOT NULL,
    usuario_id uuid,
    fecha date DEFAULT CURRENT_DATE,
    descripcion_tareas text,
    creado_el timestamp with time zone DEFAULT now()
);
ALTER TABLE public.partes_jefe OWNER TO supabase_admin;

ALTER TABLE public.partes_jefe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partes_jefe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.partes_jefe_obras (
    id bigint NOT NULL,
    parte_jefe_id bigint,
    obra_id bigint,
    porcentaje numeric(5,2) NOT NULL,
    CONSTRAINT porcentaje_valido CHECK (((porcentaje > (0)::numeric) AND (porcentaje <= (100)::numeric)))
);
ALTER TABLE public.partes_jefe_obras OWNER TO supabase_admin;

ALTER TABLE public.partes_jefe_obras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partes_jefe_obras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.partes_trabajo (
    id bigint NOT NULL,
    usuario_id uuid,
    point_obra_id bigint,
    fecha date NOT NULL,
    horas_normales numeric(4,2) DEFAULT 8.0,
    horas_extra numeric(4,2) DEFAULT 0.0,
    descripcion_tareas text,
    creado_el timestamp with time zone DEFAULT now(),
    especialidad text,
    CONSTRAINT fecha_max_dos_semanas CHECK ((fecha >= (CURRENT_DATE - '14 days'::interval)))
);
ALTER TABLE public.partes_trabajo OWNER TO supabase_admin;

ALTER TABLE public.partes_trabajo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partes_trabajo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.perfiles (
                                 id uuid NOT NULL,
                                 email text,
                                 nombre_completo text,
                                 codigo text,
                                 rol public.usuario_rol DEFAULT 'OPERARIO'::public.usuario_rol,
                                 jefe_directo_id uuid,
                                 activo boolean DEFAULT true,
                                 creado_el timestamp with time zone DEFAULT now(),
                                 postventa boolean DEFAULT false
);
ALTER TABLE public.perfiles OWNER TO supabase_admin;

ALTER TABLE ONLY public.asignaciones_obra ADD CONSTRAINT asignaciones_obra_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.obras ADD CONSTRAINT obras_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.partes_jefe_obras ADD CONSTRAINT partes_jefe_obras_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.partes_jefe ADD CONSTRAINT partes_jefe_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.partes_trabajo ADD CONSTRAINT partes_trabajo_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.perfiles ADD CONSTRAINT perfiles_codigo_key UNIQUE (codigo);
ALTER TABLE ONLY public.perfiles ADD CONSTRAINT perfiles_email_key UNIQUE (email);
ALTER TABLE ONLY public.perfiles ADD CONSTRAINT perfiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.asignaciones_obra ADD CONSTRAINT unica_asignacion_perfil_obra UNIQUE (perfil_id, obra_id);

CREATE INDEX idx_asignacion_obra_obra ON public.asignaciones_obra USING btree (obra_id);
CREATE INDEX idx_asignacion_obra_perfil ON public.asignaciones_obra USING btree (perfil_id);
CREATE INDEX idx_partes_jefe_obras ON public.partes_jefe_obras USING btree (parte_jefe_id);
CREATE INDEX idx_partes_jefe_obras_v2 ON public.partes_jefe_obras USING btree (parte_jefe_id);
CREATE INDEX idx_partes_jefe_usuario ON public.partes_jefe USING btree (usuario_id);
CREATE INDEX idx_partes_jefe_usuario_v2 ON public.partes_jefe USING btree (usuario_id);
CREATE INDEX idx_partes_obra_id ON public.partes_trabajo USING btree (point_obra_id);
CREATE INDEX idx_partes_usuario_id ON public.partes_trabajo USING btree (usuario_id);
CREATE INDEX idx_perfiles_codigo ON public.perfiles USING btree (codigo);
CREATE INDEX idx_perfiles_jefe ON public.perfiles USING btree (jefe_directo_id);
CREATE INDEX idx_perfiles_rol ON public.perfiles USING btree (rol);

ALTER TABLE ONLY public.asignaciones_obra ADD CONSTRAINT asignaciones_obra_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.asignaciones_obra ADD CONSTRAINT asignaciones_obra_perfil_id_fkey FOREIGN KEY (perfil_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.partes_jefe_obras ADD CONSTRAINT partes_jefe_obras_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.partes_jefe_obras ADD CONSTRAINT partes_jefe_obras_parte_jefe_id_fkey FOREIGN KEY (parte_jefe_id) REFERENCES public.partes_jefe(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.partes_jefe ADD CONSTRAINT partes_jefe_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.partes_trabajo ADD CONSTRAINT partes_trabajo_point_obra_id_fkey FOREIGN KEY (point_obra_id) REFERENCES public.obras(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.partes_trabajo ADD CONSTRAINT partes_trabajo_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.perfiles ADD CONSTRAINT perfiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.perfiles ADD CONSTRAINT perfiles_jefe_directo_id_fkey FOREIGN KEY (jefe_directo_id) REFERENCES public.perfiles(id) ON DELETE SET NULL;

CREATE OR REPLACE FUNCTION sync_user_role()
RETURNS TRIGGER AS $$
BEGIN
UPDATE auth.users
SET raw_user_meta_data = jsonb_set(raw_user_meta_data, '{rol}', TO_JSONB(NEW.rol))
WHERE id = NEW.id;
RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_role_change
    AFTER UPDATE OF rol ON public.perfiles
    FOR EACH ROW
    EXECUTE FUNCTION sync_user_role();
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();