-- ==========================================
-- 1. TIPOS Y ENUMERACIONES (SEGURO)
-- ==========================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'usuario_rol') THEN
CREATE TYPE public.usuario_rol AS ENUM (
            'ADMINISTRACION',
            'GESTION',
            'OPERARIO',
            'JEFE_DE_OBRA',
            'ENCARGADO_DE_OBRA'
        );
END IF;
END $$;

-- ==========================================
-- 2. TABLAS (CON "IF NOT EXISTS")
-- ==========================================

-- Obras
CREATE TABLE IF NOT EXISTS public.obras (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            nombre TEXT NOT NULL,
                                            ubicacion TEXT NOT NULL,
                                            municipio TEXT NOT NULL,
                                            poblacion TEXT NOT NULL,
                                            fecha_inicio DATE DEFAULT CURRENT_DATE,
                                            activa BOOLEAN DEFAULT TRUE,
                                            creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

-- Perfiles
CREATE TABLE IF NOT EXISTS public.perfiles (
                                               id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
                                               email TEXT UNIQUE,
                                               nombre_completo TEXT,
                                               rol public.usuario_rol DEFAULT 'OPERARIO',
                                               activo BOOLEAN DEFAULT TRUE,
                                               creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

-- Partes de Trabajo
CREATE TABLE IF NOT EXISTS public.partes_trabajo (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     usuario_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
    point_obra_id BIGINT REFERENCES public.obras(id) ON DELETE SET NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    horas_normales DECIMAL(4,2) DEFAULT 8.0,
    horas_extra DECIMAL(4,2) DEFAULT 0.0,
    descripcion_tareas TEXT,
    firmado BOOLEAN DEFAULT FALSE,
    creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

-- ==========================================
-- 3. ÍNDICES DE RENDIMIENTO
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_perfiles_rol ON public.perfiles(rol);
CREATE INDEX IF NOT EXISTS idx_partes_usuario_id ON public.partes_trabajo(usuario_id);

-- ==========================================
-- 4. SEGURIDAD RLS (OPTIMIZADA)
-- ==========================================
ALTER TABLE public.obras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partes_trabajo ENABLE ROW LEVEL SECURITY;

-- Eliminamos políticas viejas para evitar duplicados al re-ejecutar
DO $$
BEGIN
    DROP POLICY IF EXISTS "Lectura global de obras" ON public.obras;
    DROP POLICY IF EXISTS "Cada uno ve su perfil" ON public.perfiles;
    DROP POLICY IF EXISTS "Cada uno ve sus partes" ON public.partes_trabajo;
    DROP POLICY IF EXISTS "Usuarios insertan sus partes" ON public.partes_trabajo;
END $$;

-- Creamos las políticas con la optimización de (SELECT auth.uid())
CREATE POLICY "Lectura global de obras" ON public.obras
FOR SELECT USING ((SELECT auth.role()) = 'authenticated');

CREATE POLICY "Cada uno ve su perfil" ON public.perfiles
FOR SELECT USING ((SELECT auth.uid()) = id);

CREATE POLICY "Cada uno ve sus partes" ON public.partes_trabajo
FOR SELECT USING ((SELECT auth.uid()) = usuario_id);

CREATE POLICY "Usuarios insertan sus partes" ON public.partes_trabajo
FOR INSERT WITH CHECK ((SELECT auth.uid()) = usuario_id);

-- ==========================================
-- 5. AUTOMATIZACIÓN (REEMPLAZO SEGURO)
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
INSERT INTO public.perfiles (id, email, nombre_completo, rol)
VALUES (
           new.id,
           new.email,
           COALESCE(new.raw_user_meta_data->>'full_name', 'Nuevo Usuario'),
           'OPERARIO'
       )
    ON CONFLICT (id) DO NOTHING; -- Clave en producción para no dar error si el usuario ya existe
RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 6. DATOS (SOLO SI NO EXISTEN)
-- ==========================================
INSERT INTO public.obras (nombre, ubicacion, municipio, poblacion)
SELECT 'Castanyete 3', 'Calle Castanyete 3', 'Palma', 'Palma'
    WHERE NOT EXISTS (SELECT 1 FROM public.obras WHERE nombre = 'Castanyete 3');