-- 1. Crear el tipo ENUM
CREATE TYPE public.usuario_rol AS ENUM (
    'ADMINISTRACION',
    'GESTION',
    'OPERARIO',
    'JEFE_DE_OBRA',
    'ENCARGADO'
);

-- 2. Crear Función para nuevos usuarios
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
INSERT INTO public.perfiles (id, email, nombre_completo, rol)
VALUES (
           new.id,
           new.email,
           COALESCE(new.raw_user_meta_data->>'full_name', 'Nuevo Usuario'),
           COALESCE(
                   (new.raw_user_meta_data->>'rol')::public.usuario_rol,
                   'OPERARIO'
           )
       );
RETURN NEW;
END;
$$;

-- 3. Crear Tablas y Secuencias
CREATE TABLE public.asignaciones_obra (
                                          id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                          perfil_id uuid,
                                          obra_id bigint,
                                          fecha_asignacion timestamp with time zone DEFAULT now()
);

CREATE TABLE public.obras (
                              id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                              nombre text NOT NULL,
                              ubicacion text NOT NULL,
                              municipio text NOT NULL,
                              poblacion text NOT NULL,
                              codigo text NOT NULL UNIQUE ,
                              activa boolean DEFAULT true,
                              creado_el timestamp with time zone DEFAULT now(),
                              especialidad TEXT CHECK (especialidad IN ('ELECTRICIDAD', 'FONTANERIA'))
);

CREATE TABLE public.partes_jefe (
                                    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                    usuario_id uuid,
                                    fecha date DEFAULT CURRENT_DATE,
                                    descripcion_tareas text,
                                    creado_el timestamp with time zone DEFAULT now()
);

CREATE TABLE public.partes_jefe_obras (
                                          id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                          parte_jefe_id bigint,
                                          obra_id bigint,
                                          porcentaje numeric(5,2) NOT NULL,
                                          CONSTRAINT porcentaje_valido CHECK (porcentaje > 0 AND porcentaje <= 100)
);

CREATE TABLE public.partes_trabajo (
                                       id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                       usuario_id uuid,
                                       point_obra_id bigint,
                                       fecha date NOT NULL,
                                       horas_normales numeric(4,2) DEFAULT 8.0,
                                       horas_extra numeric(4,2) DEFAULT 0.0,
                                       descripcion_tareas text,
                                       creado_el timestamp with time zone DEFAULT now(),
                                       especialidad text,
                                       CONSTRAINT fecha_max_dos_semanas CHECK (fecha >= (CURRENT_DATE - '14 days'::interval))
);

CREATE TABLE public.perfiles (
                                 id uuid PRIMARY KEY NOT NULL,
                                 email text UNIQUE,
                                 nombre_completo text,
                                 codigo text UNIQUE,
                                 rol public.usuario_rol DEFAULT 'OPERARIO'::public.usuario_rol,
                                 jefe_directo_id uuid,
                                 activo boolean DEFAULT true,
                                 creado_el timestamp with time zone DEFAULT now(),
                                 postventa boolean DEFAULT false
);

-- 4. Restricciones de Clave Foránea (Foreign Keys)
ALTER TABLE public.asignaciones_obra ADD CONSTRAINT asignaciones_obra_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id) ON DELETE CASCADE;
ALTER TABLE public.asignaciones_obra ADD CONSTRAINT asignaciones_obra_perfil_id_fkey FOREIGN KEY (perfil_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;
ALTER TABLE public.asignaciones_obra ADD CONSTRAINT unica_asignacion_perfil_obra UNIQUE (perfil_id, obra_id);

ALTER TABLE public.partes_jefe_obras ADD CONSTRAINT partes_jefe_obras_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id) ON DELETE SET NULL;
ALTER TABLE public.partes_jefe_obras ADD CONSTRAINT partes_jefe_obras_parte_jefe_id_fkey FOREIGN KEY (parte_jefe_id) REFERENCES public.partes_jefe(id) ON DELETE CASCADE;

ALTER TABLE public.partes_jefe ADD CONSTRAINT partes_jefe_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;

ALTER TABLE public.partes_trabajo ADD CONSTRAINT partes_trabajo_point_obra_id_fkey FOREIGN KEY (point_obra_id) REFERENCES public.obras(id) ON DELETE SET NULL;
ALTER TABLE public.partes_trabajo ADD CONSTRAINT partes_trabajo_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;

ALTER TABLE public.perfiles ADD CONSTRAINT perfiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.perfiles ADD CONSTRAINT perfiles_jefe_directo_id_fkey FOREIGN KEY (jefe_directo_id) REFERENCES public.perfiles(id) ON DELETE SET NULL;

-- 5. Índices para rendimiento
CREATE INDEX idx_asignacion_obra_obra ON public.asignaciones_obra(obra_id);
CREATE INDEX idx_asignacion_obra_perfil ON public.asignaciones_obra(perfil_id);
CREATE INDEX idx_partes_jefe_obras ON public.partes_jefe_obras(parte_jefe_id);
CREATE INDEX idx_partes_jefe_usuario ON public.partes_jefe(usuario_id);
CREATE INDEX idx_partes_obra_id ON public.partes_trabajo(point_obra_id);
CREATE INDEX idx_partes_usuario_id ON public.partes_trabajo(usuario_id);
CREATE INDEX idx_perfiles_codigo ON public.perfiles(codigo);
CREATE INDEX idx_perfiles_jefe ON public.perfiles(jefe_directo_id);

-- 6. Sincronización de Roles
CREATE OR REPLACE FUNCTION sync_user_role()
RETURNS TRIGGER AS $$
BEGIN
UPDATE auth.users
SET raw_user_meta_data = jsonb_set(COALESCE(raw_user_meta_data, '{}'::jsonb), '{rol}', TO_JSONB(NEW.rol))
WHERE id = NEW.id;
RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Triggers Finales
CREATE TRIGGER on_role_change
    AFTER UPDATE OF rol ON public.perfiles
    FOR EACH ROW
    EXECUTE FUNCTION sync_user_role();

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();