-- ==========================================
-- 1. TIPOS Y ENUMERACIONES (SEGURO)
-- ==========================================
DO $$
BEGIN
    -- Creamos el tipo solo si no existe
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'usuario_rol') THEN
CREATE TYPE usuario_rol AS ENUM ('ADMINISTRACION', 'GESTION', 'OPERARIO', 'JEFE_DE_OBRA', 'ENCARGADO_DE_OBRA');
END IF;
END $$;

-- ==========================================
-- 2. TABLAS (CON "IF NOT EXISTS")
-- ==========================================

CREATE TABLE IF NOT EXISTS public.obras (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            nombre TEXT NOT NULL,
                                            ubicacion TEXT NOT NULL,
                                            municipio TEXT NOT NULL,
                                            poblacion TEXT NOT NULL,
                                            fecha_inicio DATE DEFAULT CURRENT_DATE,
                                            activa BOOLEAN DEFAULT TRUE,
                                            creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

CREATE TABLE IF NOT EXISTS public.perfiles (
                                               id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
                                               email TEXT UNIQUE,
                                               nombre_completo TEXT,
                                               rol usuario_rol DEFAULT 'OPERARIO',
                                               activo BOOLEAN DEFAULT TRUE,
                                               creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

CREATE TABLE IF NOT EXISTS public.partes_trabajo (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     usuario_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
    obra_id BIGINT REFERENCES public.obras(id) ON DELETE SET NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    horas_normales DECIMAL(4,2) DEFAULT 8.0,
    horas_extra DECIMAL(4,2) DEFAULT 0.0,
    descripcion_tareas TEXT,
    firmado BOOLEAN DEFAULT FALSE,
    creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

-- ==========================================
-- 3. AUTOMATIZACIÓN (TRIGGERS SEGUROS)
-- ==========================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
INSERT INTO public.perfiles (id, email, nombre_completo, rol)
VALUES (
           new.id,
           new.email,
           COALESCE(new.raw_user_meta_data->>'full_name', 'Nuevo Usuario'),
           'OPERARIO'
       )
    ON CONFLICT (id) DO NOTHING; -- Evita errores si el usuario ya existe
RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Borramos y recreamos el trigger para asegurar que usa la última versión de la función
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 4. SEGURIDAD DE PRODUCCIÓN (RLS)
-- ==========================================
-- Activamos el Row Level Security en todas las tablas
ALTER TABLE public.obras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partes_trabajo ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS BÁSICAS:
-- 1. Cualquiera autenticado puede ver las obras activas
CREATE POLICY "Usuarios pueden ver obras" ON public.obras
FOR SELECT USING (auth.role() = 'authenticated');

-- 2. Los usuarios solo pueden ver y editar SU PROPIO perfil
CREATE POLICY "Usuarios ven su propio perfil" ON public.perfiles
FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Usuarios actualizan su propio perfil" ON public.perfiles
FOR UPDATE USING (auth.uid() = id);

-- 3. Los operarios solo ven sus propios partes de trabajo
CREATE POLICY "Usuarios ven sus propios partes" ON public.partes_trabajo
FOR SELECT USING (auth.uid() = usuario_id);

CREATE POLICY "Usuarios crean sus propios partes" ON public.partes_trabajo
FOR INSERT WITH CHECK (auth.uid() = usuario_id);