-- ==========================================
-- 1. TIPOS Y ENUMERACIONES (Roles de Lum)
-- ==========================================
DO $$
BEGIN
    -- Limpieza por si acaso hubo intentos previos
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'usuario_rol') THEN
DROP TYPE usuario_rol CASCADE;
END IF;

    -- Roles: ADMINISTRACION, GESTION, OPERARIO, JEFE_DE_OBRA, ENCARGADO
CREATE TYPE usuario_rol AS ENUM ('ADMINISTRACION', 'GESTION', 'OPERARIO', 'JEFE_DE_OBRA', 'ENCARGADO');
END $$;

-- ==========================================
-- 2. TABLAS PRINCIPALES
-- ==========================================

-- Tabla de Obras
CREATE TABLE IF NOT EXISTS public.obras (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            nombre TEXT NOT NULL,
                                            ubicacion TEXT NOT NULL,
                                            municipio TEXT NOT NULL,
                                            poblacion TEXT NOT NULL,
                                            fecha_inicio DATE DEFAULT CURRENT_DATE,
                                            activa BOOLEAN DEFAULT TRUE,
                                            creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

-- Tabla de Perfiles
CREATE TABLE IF NOT EXISTS public.perfiles (
                                               id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
                                               email TEXT UNIQUE,
                                               nombre_completo TEXT,
                                               rol usuario_rol DEFAULT 'OPERARIO',
                                               activo BOOLEAN DEFAULT TRUE,
                                               creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

-- Tabla de Partes de Trabajo
CREATE TABLE IF NOT EXISTS public.partes_trabajo (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     usuario_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
    obra_id BIGINT REFERENCES public.obras(id) ON DELETE SET NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    horas_normales DECIMAL(4,2) DEFAULT 8.0,
    horas_extra DECIMAL(4,2) DEFAULT 0.0,
    descripcion_tareas TEXT,
    firmado BOOLEAN DEFAULT FALSE,
    creado_el TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

-- ==========================================
-- 3. AUTOMATIZACIÓN (TRIGGERS)
-- ==========================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
INSERT INTO public.perfiles (id, email, nombre_completo, rol)
VALUES (
           new.id,
           new.email,
           COALESCE(new.raw_user_meta_data->>'full_name', 'Nuevo Usuario'),
           'OPERARIO' -- Importante: Debe coincidir con uno de los nombres del ENUM
       );
RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 4. DATOS DE PRUEBA
-- ==========================================
INSERT INTO public.obras (nombre, ubicacion, municipio, poblacion)
VALUES
    ('Castanyete 3', 'Calle Castanyete 3', 'Palma', 'Palma'),
    ('Solleric 3', 'Plaza Solleric', 'Sóller', 'Sóller')
    ON CONFLICT DO NOTHING;